///@name get-prompts
GET http://localhost:3333/prompts 

###

///@name get-videos
POST http://localhost:3333/videos 
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="example.mp3"
Content-Type: audio/mpeg

< ./example.mp3
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###

///create transcription
POST http://localhost:3333/videos/50900704-99c1-4c8e-b5d2-72bd7d42ee2e/transcription
Content-Type: application/json

{
  "prompt":"fake naty, see bum"
}

###
///generate ai completion
POST http://localhost:3333/ai/complete
Content-Type: application/json

{
  "videoId":"50900704-99c1-4c8e-b5d2-72bd7d42ee2e",
  "template":0.5,
  "prompt":"Gere um resumo sucinto da transcrição do vídeo informada a seguir: '''{transcription}'''"
}